version: 0.0
os: linux

files:
  - source: frontend/
    destination: /home/ec2-user/snaptweet/frontend/
  - source: backend/
    destination: /home/ec2-user/snaptweet/backend/
  - source: scripts/
    destination: /home/ec2-user/snaptweet/scripts/

hooks:
  AfterInstall:
    # Ensure the scripts are executable
    - location: /bin/bash
      timeout: 180
      runas: ec2-user
      arguments:
        - -c
        - |
          chmod +x /home/ec2-user/snaptweet/scripts/install_dependencies.sh
          chmod +x /home/ec2-user/snaptweet/scripts/start_containers.sh

    # Now run the install_dependencies.sh script
    - location: /home/ec2-user/snaptweet/scripts/install_dependencies.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    # Run start_containers.sh script as ec2-user
    - location: /home/ec2-user/snaptweet/scripts/start_containers.sh
      timeout: 180
      runas: ec2-user
