version: 0.0
os: linux

files:
  # Ensure that the paths from the root of your deployment archive are correct
  - source: frontend/
    destination: /home/ec2-user/snaptweet/frontend/
  - source: backend/
    destination: /home/ec2-user/snaptweet/backend/
  - source: scripts/
    destination: /home/ec2-user/snaptweet/scripts/

hooks:
  AfterInstall:
    # Make scripts executable after they are copied
    - location: /bin/bash
      timeout: 180
      runas: ec2-user
      arguments:
        - -c
        - |
          chmod +x /home/ec2-user/snaptweet/scripts/install_dependencies.sh
          chmod +x /home/ec2-user/snaptweet/scripts/start_containers.sh

    # Run the install_dependencies.sh script
    - location: /home/ec2-user/snaptweet/scripts/install_dependencies.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    # Start the containers once the installation is complete
    - location: /home/ec2-user/snaptweet/scripts/start_containers.sh
      timeout: 180
      runas: ec2-user
