version: 0.0
os: linux

files:
  # Ensure that the paths from the root of your deployment archive are correct
  - source: frontend/
    destination: /home/ec2-user/snaptweet/frontend/
  - source: backend/
    destination: /home/ec2-user/snaptweet/backend/
  - source: scripts/
    destination: /home/ec2-user/snaptweet/scripts/

hooks:
  AfterInstall:
    # This will run the script to install dependencies after the files have been copied
    - location: /home/ec2-user/snaptweet/scripts/install_dependencies.sh
      timeout: 180
      runas: ec2-user

    # Add a command to ensure that the install_dependencies.sh and start_containers.sh scripts are executable
    - location: /bin/bash
      timeout: 180
      runas: ec2-user
      arguments:
        - -c
        - |
          chmod +x /home/ec2-user/snaptweet/scripts/install_dependencies.sh
          chmod +x /home/ec2-user/snaptweet/scripts/start_containers.sh

  ApplicationStart:
    # This will start the containers once the installation is complete
    - location: /home/ec2-user/snaptweet/scripts/start_containers.sh
      timeout: 180
      runas: ec2-user
