name: Run Backend Tests

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/**" # optional, if you're editing the workflow
    branches:
      - main
      - dev

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      MONGO_URI: mongodb+srv://rishhidev:6TcOsmeUIeOkKvtB@cluster0.3jvli.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      NODE_ENV: test
      JWT_SECRET: your_secret_key

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - run: npm install
      - run: npm run test
